language: node_js
node_js:
- "10"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run bdd/Testing_with_BDD.postman_collection.json -e bdd/heroku.postman_environment.json